class_name CommandDomains
extends RefCounted
## Command-name registry; callers retain authority, preview and outcome handling.
const AIR = preload("res://scripts/sim/cmds_air.gd")
const CREW = preload("res://scripts/sim/cmds_crew.gd")
const GROUND = preload("res://scripts/sim/cmds_ground.gd")
const TRADE = preload("res://scripts/sim/cmds_trade.gd")
const COURT = preload("res://scripts/sim/cmds_court.gd")
const ORG = preload("res://scripts/sim/cmds_org.gd")

static func handlers() -> Dictionary:
	return {
		"phone_answer": Callable(ORG, "_cmd_phone_answer"),
		"phone_decline": Callable(ORG, "_cmd_phone_decline"),
		"accept_job": Callable(AIR, "_cmd_accept_job"),
		"drop_job": Callable(AIR, "_cmd_drop_job"),
		"move_item": Callable(AIR, "_cmd_move_item"),
		"loadmaster": Callable(AIR, "_cmd_loadmaster"),
		"set_fuel": Callable(AIR, "_cmd_set_fuel"),
		"fill_ferry": Callable(AIR, "_cmd_fill_ferry"),
		"buy_aircraft": Callable(AIR, "_cmd_buy_aircraft"),
		"buy_gear": Callable(AIR, "_cmd_buy_gear"),
		"hire_spotter": Callable(CREW, "_cmd_hire_spotter"),
		"spotter_move": Callable(CREW, "_cmd_spotter_move"),
		"squawk": Callable(AIR, "_cmd_squawk"),
		"upgrade": Callable(AIR, "_cmd_upgrade"),
		"jam": Callable(AIR, "_cmd_jam"),
		"transponder": Callable(AIR, "_cmd_transponder"),
		"turn_around": Callable(AIR, "_cmd_turn_around"),
		"autopilot": Callable(AIR, "_cmd_autopilot"),
		"kick": Callable(AIR, "_cmd_kick"),
		"auto_kick": Callable(AIR, "_cmd_auto_kick"),
		"pump": Callable(AIR, "_cmd_pump"),
		"call_boat": Callable(AIR, "_cmd_call_boat"),
		"cutter_goto": Callable(AIR, "_cmd_cutter_goto"),
		"boat_goto": Callable(AIR, "_cmd_boat_goto"),
		"confirm": Callable(AIR, "_cmd_confirm"),
		"hq": Callable(ORG, "_cmd_hq"),
		"chat": Callable(ORG, "_cmd_chat"),
		"radio_channel": Callable(ORG, "_cmd_radio_channel"),
		"launch": Callable(AIR, "_cmd_launch"),
		"dispatch": Callable(AIR, "_cmd_dispatch"),
		"recall": Callable(AIR, "_cmd_recall"),
		"claim_unit": Callable(AIR, "_cmd_claim_unit"),
		"release_unit": Callable(AIR, "_cmd_release_unit"),
		"encrypt": Callable(AIR, "_cmd_encrypt"),
		"aerostat": Callable(AIR, "_cmd_aerostat"),
		"gun_mode": Callable(AIR, "_cmd_gun_mode"),
		"sell_weapons": Callable(GROUND, "_cmd_sell_weapons"),
		"buy_weapons": Callable(GROUND, "_cmd_buy_weapons"),
		"set_cache": Callable(GROUND, "_cmd_set_cache"),
		"squad_order": Callable(GROUND, "_cmd_squad_order"),
		"field_order": Callable(GROUND, "_cmd_field_order"),
		"rackets": Callable(GROUND, "_cmd_rackets"),
		"stash_works": Callable(GROUND, "_cmd_stash_works"),
		"analyst": Callable(ORG, "_cmd_analyst"),
		"casino": Callable(TRADE, "_cmd_casino"),
		"acid_barter": Callable(TRADE, "_cmd_acid_barter"),
		"acid_sell": Callable(TRADE, "_cmd_acid_sell"),
		"acid_auto": Callable(TRADE, "_cmd_acid_auto"),
		"buy_vehicle": Callable(TRADE, "_cmd_buy_vehicle"),
		"sell_vehicle": Callable(TRADE, "_cmd_sell_vehicle"),
		"use_vehicle": Callable(TRADE, "_cmd_use_vehicle"),
		"fleet_auto": Callable(TRADE, "_cmd_fleet_auto"),
		"casino_play": Callable(TRADE, "_cmd_casino_play"),
		"casino_case": Callable(TRADE, "_cmd_casino_case"),
		"service": Callable(CREW, "_cmd_service"),
		"stop_work": Callable(CREW, "_cmd_stop_work"),
		"inspect": Callable(CREW, "_cmd_inspect"),
		"plant_beacon": Callable(ORG, "_cmd_plant_beacon"),
		"race_enter": Callable(TRADE, "_cmd_race_enter"),
		"recruit_squad": Callable(GROUND, "_cmd_recruit_squad"),
		"disband_squad": Callable(GROUND, "_cmd_disband_squad"),
		"investigate_agency": Callable(ORG, "_cmd_investigate_agency"),
		"island_ship": Callable(TRADE, "_cmd_island_ship"),
		"buy_passage": Callable(TRADE, "_cmd_buy_passage"),
		"airport_crackdown": Callable(TRADE, "_cmd_airport_crackdown"),
		"port_inspections": Callable(TRADE, "_cmd_port_inspections"),
		"court_bail": Callable(COURT, "_cmd_court_bail"),
		"court_hire": Callable(COURT, "_cmd_court_hire"),
		"court_motion": Callable(COURT, "_cmd_court_motion"),
		"court_tamper": Callable(COURT, "_cmd_court_tamper"),
		"court_bribe": Callable(COURT, "_cmd_court_bribe"),
		"court_plea": Callable(COURT, "_cmd_court_plea"),
		"court_cooperate": Callable(COURT, "_cmd_court_cooperate"),
		"court_appeal": Callable(COURT, "_cmd_court_appeal"),
		"court_wait": Callable(COURT, "_cmd_court_wait"),
		"court_no_bail": Callable(COURT, "_cmd_court_no_bail"),
		"court_immunity": Callable(COURT, "_cmd_court_immunity"),
		"court_forfeiture": Callable(COURT, "_cmd_court_forfeiture"),
		"court_charge": Callable(COURT, "_cmd_court_charge"),
		"court_offer_plea": Callable(COURT, "_cmd_court_offer_plea"),
		"sell_product": Callable(TRADE, "_cmd_sell_product"),
		"move_goods": Callable(TRADE, "_cmd_move_goods"),
		"move_cash": Callable(TRADE, "_cmd_move_cash"),
		"cash_round": Callable(TRADE, "_cmd_cash_round"),
		"goods_round": Callable(TRADE, "_cmd_goods_round"),
		"escort_truck": Callable(GROUND, "_cmd_escort_truck"),
		"tutorial": Callable(ORG, "_cmd_tutorial"),
		"move_armoury": Callable(GROUND, "_cmd_move_armoury"),
		"load_cash": Callable(TRADE, "_cmd_load_cash"),
		"unload_cash": Callable(TRADE, "_cmd_unload_cash"),
		"street_sweep": Callable(GROUND, "_cmd_street_sweep"),
		"trace_money": Callable(ORG, "_cmd_trace_money"),
		"hire_worker": Callable(CREW, "_cmd_hire_worker"),
		"fire_worker": Callable(CREW, "_cmd_fire_worker"),
		"pay_bonus": Callable(CREW, "_cmd_pay_bonus"),
		"pay_worker_lawyer": Callable(CREW, "_cmd_pay_worker_lawyer"),
		"post_lookout": Callable(CREW, "_cmd_post_lookout"),
		"offer_worker_deal": Callable(CREW, "_cmd_offer_worker_deal"),
		"family_accept": Callable(ORG, "_cmd_family_accept"),
		"family_decline": Callable(ORG, "_cmd_family_decline"),
		"family_probe": Callable(ORG, "_cmd_family_probe"),
		"family_stall": Callable(ORG, "_cmd_family_stall"),
		"pay_tribute": Callable(TRADE, "_cmd_pay_tribute"),
		"rico_case": Callable(ORG, "_cmd_rico_case"),
		"raid_stash": Callable(GROUND, "_cmd_raid_stash"),
	}
