extends SceneTree
## Audit every airstrip on a map: geometry, both approaches, the ground past each end, what the
## roster can use it for, and (with --bot) whether the pilot bot can take off from and land on it.
##
##   godot --headless --path . --script res://tools/strip_audit.gd -- [--map city|N] [--bot] [--aircraft c172p,c182] [--out docs/STRIPS.md]
##
## A strip is flagged when: it is narrower than 1.6 wingspans of the smallest aircraft that would use it,
## an approach path (3 deg, 4.5 deg for a bush strip) is pierced by terrain or trees, the ground past an
## end drops away or is water, its length can't fit an aircraft's landing roll with a 1.6 margin, or the
## bot fails a trial. Exit code is 0; the report is the result.

const APPROACH_DEG := 3.0
const BUSH_APPROACH_DEG := 4.5
const ROLL_MARGIN := 1.6
const SPAN_MARGIN := 1.6

const NOTES := """## Reading the results

- **One-way strips, by design.** QRY end 0 and PNR end 0 have terrain or mountain in the approach path
  (the flag says how far up it is), so land toward the open end and take off away from the high ground.
- **EGL is a mesa.** About 170 m of cliff past both ends: a short field, and an overrun is fatal.
- **Widths.** The three mountain strips were 12, 14 and 15 m for an 11 m wing; they are now 18 m
  (`MapCity._strip_specs`), and `tests/test_strips.gd` keeps every strip at 1.5 wingspans or more.
  Twin Otter-sized aircraft use 20 m strips, which is tight but real.
- **Bot failures left on the mountain strips.** The Cessna 182 overruns the 240 to 380 m strips at light
  load, and the Cessna 172 cannot leave them at half load. The job generator can therefore send a
  load somewhere it cannot fly out of; that is a balance question for the K3 re-fly (docs/ROADMAP.md),
  not a strip defect, so it is reported here and not papered over.
- **Landing rules** now allow a graded shoulder beside the strip (`Session.SHOULDER_M`), a wingtip strike
  needs 18 degrees of bank, and the gear holds to 1.25 times its rated sink rate (a hard landing
  between 1x and 1.25x costs the fragile-cargo pay, as before)."""

var world: World
var flags: Array = []  ## [code, text]


func _initialize() -> void:
	var args := OS.get_cmdline_user_args()
	var map_seed := MapCity.SEED
	var bot := false
	var keys: Array = ["c172p"]
	var out := ""
	var i := 0
	while i < args.size():
		match args[i]:
			"--map":
				i += 1
				map_seed = MapCity.SEED if args[i] == "city" else int(args[i])
			"--bot":
				bot = true
			"--aircraft":
				i += 1
				keys = Array(args[i].split(","))
			"--out":
				i += 1
				out = args[i]
		i += 1
	World.use_map(map_seed)
	world = World.new()
	var lines := ["# Airstrip audit", "",
		"Map seed %d, generated by `tools/strip_audit.gd`. Approach paths are checked against terrain and trees at %.1f deg (%.1f deg for bush strips); landing rolls use each aircraft's own estimate with a %.1fx margin." % [map_seed, APPROACH_DEG, BUSH_APPROACH_DEG, ROLL_MARGIN], ""]
	lines.append("| strip | surface | length x width | elev | kind | approach clearance (end 0 / end 1) | past the ends | aircraft it fits (landing) |")
	lines.append("|---|---|---|---|---|---|---|---|")
	for af in World.AIRFIELDS:
		lines.append(_row(af))
	lines.append("")
	if bot:
		lines.append_array(_bot_section(keys))
	lines.append_array(NOTES.split("
"))
	lines.append("")
	lines.append("## Flags")
	lines.append("")
	if flags.is_empty():
		lines.append("None.")
	for f in flags:
		lines.append("- **%s**: %s" % [f[0], f[1]])
	var text := "\n".join(lines) + "\n"
	print(text)
	if out != "":
		var path := out if out.is_absolute_path() else ProjectSettings.globalize_path("res://").path_join(out)
		var f := FileAccess.open(path, FileAccess.WRITE)
		if f != null:
			f.store_string(text)
			print("wrote ", path)
	quit()


func _row(af: Airfield) -> String:
	var elev: float = world.airfield_elev(af)
	var deg := BUSH_APPROACH_DEG if af.kind in ["bush", "shady"] else APPROACH_DEG
	var clear := []
	for end in [0, 1]:
		var c := _approach_clearance(af, end, deg)
		clear.append(c)
		if c[0] < 0.0:
			_flag(af, "approach to end %d is pierced by %s %.0f m up at %.0f m out (%.1f deg path)" % [end, c[2], -c[0], c[1], deg])
	var past := []
	for end in [0, 1]:
		var p := _past_end(af, end, elev)
		past.append(p)
		if p[0] > 12.0:
			_flag(af, "the ground drops %.0f m within 250 m past end %d" % [p[0], end])
		if p[1]:
			_flag(af, "water within 250 m past end %d" % end)
	var fits := []
	var spans := []
	for k in Aircraft.ROSTER:
		var spec: Aircraft.Spec = Aircraft.ROSTER[k]
		var w: float = spec.mtow_lb * 0.85
		var need := spec.est_landing_roll(w, elev) * ROLL_MARGIN
		if need <= af.length:
			fits.append(k)
		if af.width < spec.visual.span_m * SPAN_MARGIN and need <= af.length:
			spans.append("%s (span %.1f m)" % [k, spec.visual.span_m])
	if not spans.is_empty():
		_flag(af, "%.0f m wide is under %.1f wingspans for %s" % [af.width, SPAN_MARGIN, ", ".join(spans)])
	if fits.is_empty():
		_flag(af, "no aircraft in the roster fits %.0f m with a %.1fx margin" % [af.length, ROLL_MARGIN])
	var trees := _trees_on_strip(af)
	if trees > 0:
		_flag(af, "%d trees within the strip's width and 15 m either side of the centreline" % trees)
	return "| %s %s | %s | %.0f x %.0f m | %.0f m | %s/%s | %s / %s | %s / %s | %s |" % [af.code, af.name, af.surface, af.length, af.width,
		elev, af.kind, af.setting, _clr(clear[0]), _clr(clear[1]), _past(past[0]), _past(past[1]), ", ".join(fits)]


func _clr(c: Array) -> String:
	return "%+.0f m" % c[0]


func _past(p: Array) -> String:
	return ("water" if p[1] else "drop %.0f m" % p[0]) if (p[1] or p[0] > 1.0) else "level"


func _flag(af: Airfield, text: String) -> void:
	flags.append(["%s %s" % [af.code, af.name], text])


## Worst (path height - obstacle top) along the final approach to `end`, with where and what.
## Positive is margin; negative is the depth the terrain or a tree pierces the path.
func _approach_clearance(af: Airfield, end: int, deg: float) -> Array:
	var t: Array = af.threshold(end)
	var s := 1.0 if end == 1 else -1.0  # the approach runs outward from this end
	var elev: float = world.airfield_elev(af)
	var worst := 1e9
	var at := 0.0
	var what := "terrain"
	var d := 30.0
	while d <= 3000.0:
		var x: float = t[0] + s * af.ux * d
		var y: float = t[1] + s * af.uy * d
		var path: float = elev + 10.0 + d * tan(deg_to_rad(deg))  # 10 m over the threshold
		var g: float = world.ground(x, y)
		var top: float = world.obstacle_top(x, y, af.width * 0.5 + 12.0)
		var m := path - top
		if m < worst:
			worst = m
			at = d
			what = "trees" if top > g + 1.0 else "terrain"
		d += 30.0
	return [worst, at, what]


## [deepest drop below the strip's elevation within 250 m past the end, water there?]
func _past_end(af: Airfield, end: int, elev: float) -> Array:
	var t: Array = af.threshold(end)
	var s := -1.0 if end == 0 else 1.0
	var drop := 0.0
	var water := false
	for d in [20.0, 60.0, 120.0, 180.0, 250.0]:
		var x: float = t[0] + s * af.ux * d
		var y: float = t[1] + s * af.uy * d
		drop = maxf(drop, elev - world.terrain.height(x, y))
		water = water or world.is_water(x, y)
	return [drop, water]


func _trees_on_strip(af: Airfield) -> int:
	var n := 0
	var a := -af.length / 2.0
	while a <= af.length / 2.0:
		for lat in [-1.0, 0.0, 1.0]:
			var x: float = af.x + af.ux * a + af.uy * (lat * (af.width * 0.5 + 15.0))
			var y: float = af.y + af.uy * a - af.ux * (lat * (af.width * 0.5 + 15.0))
			if world.terrain.tree_hit(x, y, world.airfield_elev(af) + 3.0, 3.0):
				n += 1
		a += 20.0
	return n


func _bot_section(keys: Array) -> Array:
	var out := ["## Pilot bot trials", "",
		"Takeoff and landing flown by the pilot bot (`Feasibility`), light and half load. T = takeoff, L = landing.", "",
		"| strip | " + " | ".join(keys.map(func(k): return "%s light" % k)) + " | " + " | ".join(keys.map(func(k): return "%s half" % k)) + " |",
		"|---|" + "---|".repeat(keys.size() * 2)]
	for af in World.AIRFIELDS:
		var cells := []
		for load in ["light", "half"]:
			for k in keys:
				var spec: Aircraft.Spec = Aircraft.ROSTER[k]
				var elev: float = world.airfield_elev(af)
				var t: Dictionary = Feasibility.takeoff_trial(k, af.code, load)
				var l: Dictionary = Feasibility.landing_trial(k, af.code, load)
				cells.append("T%s L%s" % ["✓" if t.ok else "✗", "✓" if l.ok else "✗"])
				if not t.ok:
					_flag(af, "bot could not take off (%s, %s load): %s" % [k, load, str(t.outcome).left(70)])
				if not l.ok:
					_flag(af, "bot could not land (%s, %s load): %s" % [k, load, str(l.outcome).left(70)])
		out.append("| %s %s | %s |" % [af.code, af.name, " | ".join(cells)])
	out.append("")
	return out
